apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.appEnv }}
  {{ $key | upper }}: {{ $value | quote }}
  {{- end }}

