---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "common.selectorLabels" . | nindent 6 }}
  {{- if .Values.strategy }}
  strategy:
    {{- toYaml .Values.strategy | nindent 4 }}
  {{- end }}
  template:
    metadata:
      {{- include "pod.metadata" . | nindent 6 }}
    spec:
      {{- include "pod.spec" . | nindent 6 }}
      containers:
        {{- include "container.spec" . | nindent 8 }}

