version: 2.1
workflows:
  build_test_push:
    jobs:
      - build_test_and_push
      #- promote:
          #filters:
            #branches:
              #only:
                #- main
          #type: approval
          #requires:
            #- cypress
            #- rspec
      #- deploy:
          #filters:
            #branches:
              #only:
                #- main
          #requires:
            #- promote
jobs:
  build_test_and_push:
    machine: # executor type
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - checkout
      # Build Image
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=procare-exercise -t procare-exercise .
      # Test Image
      - run:
          name: Setup Code Climate test-reporter
          command: |
            sudo apt-get install jq
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      # Run Services
      - run:
          name: prep for tests
          command: |
            ./bin/bootstrap
            docker-compose up -d
      # Test Image
      - run:
          name: Run rspec tests
          command: |
            mkdir -p coverage
            docker-compose run -v $(pwd)/coverage:/opt/app/coverage web rspec spec
      # Report results
      - run:
          name: Report test coverage
          command: |
            sed -i 's%\/opt\/app\/%%g' coverage/coverage.json
            ./cc-test-reporter format-coverage -t simplecov coverage/coverage.json
            ./cc-test-reporter upload-coverage
      # Push Image
      - run:
          name: Push application Docker image
          command: |
            docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_ACCESS_TOKEN
            docker tag procare-exercise "pevanscfi/procare-exercise:${CIRCLE_SHA1:0:6}"
            docker push "pevanscfi/procare-exercise:${CIRCLE_SHA1:0:6}"
  deploy:
    working_directory: /
    docker:
      - image: pevanscfi/ops-toolbox:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ef:9b:5b:60:63:61:04:a9:52:32:e7:cd:0b:d7:a2:43"
      - run:
          name: Update the gitops repo
          command: |
            git config --global user.email "paul+circleci@wevans.io"
            git config --global user.name "CircleCI"
            git clone git@github.com:wevanscfi/homelab-gitops.git
            cd homelab-gitops
            yq e -i '(.spec.source.helm.parameters[] | select(.name == "image.tag")).value = "'"$CIRCLE_SHA1:0:6"'"' manifests/wevans/templates/procare-exercise.yaml
            git add manifests/wevans/templates/procare-exercise.yaml
            git commit -m "Deploy procare-exercise: ${CIRCLE_SHA1:0:6}"
            git push origin main

